
import { Language } from '../types';

export const translations = {
  en: {
    appTitle: "ECHOES_SYS//V1.0",
    corePersonality: "Core Personality",
    adjustDimensions: "Adjust dimensions to reshape personality.",
    empathy: "Empathy",
    empathyDesc: "High: Supportive, validating. Low: Detached, cold.",
    rationality: "Rationality",
    rationalityDesc: "High: Logical, analytical. Low: Impulsive, emotional.",
    humor: "Humor",
    humorDesc: "High: Witty, playful, sarcastic. Low: Serious, formal.",
    intimacy: "Intimacy",
    intimacyDesc: "High: Affectionate, touchy. Low: Professional, distant.",
    narrative: "Narrative",
    narrativeDesc: "High: Novelistic, detailed. Low: Direct, concise.",
    liveChat: "Live Chat",
    sandbox: "Sandbox",
    settings: "Settings",
    language: "Language",
    selectLanguage: "Select Interface Language",
    close: "Close",
    connectionEstablished: "Connection established.",
    configureAndSayHello: "Configure personality and say hello.",
    typeMessage: "Type your message...",
    sandboxTitle: "Simulation Sandbox",
    sandboxDesc: "Test how the current emotional profile responds to specific scenarios without affecting your main memory.",
    scenarioPrompt: "Scenario Prompt",
    enterScenario: "Enter a scenario (e.g., 'I failed my exam today...')",
    runSimulation: "Run Simulation",
    simulating: "Simulating...",
    analysisTitle: "Response Analysis",
    scenarios: [
        "I'm feeling really stressed about work today.",
        "I think we should break up. It's not working.",
        "Tell me a joke to cheer me up.",
        "I bought us tickets to that movie you mentioned!"
    ],
    // New Features
    sceneMode: "Scene Mode",
    sceneModeDesc: "Include actions & feelings (*smiles*)",
    userNickname: "Me",
    aiNickname: "Echo",
    edit: "Edit",
    regenerate: "Regenerate",
    cancel: "Cancel",
    saveAndSend: "Save & Send",
    searchHistory: "Search History",
    moments: "Moments",
    searchPlaceholder: "Search chat content...",
    noResults: "No results found.",
    general: "General",
    momentsDesc: "AI's social feed based on current personality.",
  },
  zh: {
    appTitle: "ECHOES_SYS//V1.0",
    corePersonality: "核心人格",
    adjustDimensions: "调整维度以重塑人格。",
    empathy: "共情度",
    empathyDesc: "高：支持、认可。低：疏离、冷漠。",
    rationality: "理性度",
    rationalityDesc: "高：逻辑、分析。低：冲动、情绪化。",
    humor: "幽默感",
    humorDesc: "高：风趣、顽皮、反讽。低：严肃、正式。",
    intimacy: "亲密倾向",
    intimacyDesc: "高：亲昵、肢体接触。低：专业、距离感。",
    narrative: "叙事风格",
    narrativeDesc: "高：小说式、细节丰富。低：直接、简洁。",
    liveChat: "实时对话",
    sandbox: "沙盘演练",
    settings: "设置",
    language: "语言选项",
    selectLanguage: "选择界面语言",
    close: "关闭",
    connectionEstablished: "连接已建立。",
    configureAndSayHello: "配置人格并打个招呼吧。",
    typeMessage: "输入消息...",
    sandboxTitle: "模拟沙盘",
    sandboxDesc: "在不影响主要记忆的情况下，测试当前情感侧写对特定场景的反应。",
    scenarioPrompt: "场景提示",
    enterScenario: "输入场景（例如：'我今天考试挂了...'）",
    runSimulation: "运行模拟",
    simulating: "模拟中...",
    analysisTitle: "响应分析",
    scenarios: [
        "我今天工作压力好大。",
        "我觉得我们应该分手，这样下去不行。",
        "讲个笑话哄哄我。",
        "我买了你之前提到的那部电影的票！"
    ],
    // New Features
    sceneMode: "场景模式",
    sceneModeDesc: "包含动作、心理描写（括号内容）",
    userNickname: "我",
    aiNickname: "Echo",
    edit: "修改",
    regenerate: "重新生成",
    cancel: "取消",
    saveAndSend: "保存并发送",
    searchHistory: "查找聊天记录",
    moments: "朋友圈",
    searchPlaceholder: "搜索聊天内容...",
    noResults: "未找到相关记录。",
    general: "通用",
    momentsDesc: "基于当前人格生成的社交动态。",
  }
};

export const getTranslation = (lang: Language) => translations[lang];
